// // const BASE_URL = 'http://101.0.20.71:2345'
// const BASE_URL = 'https://ag.t20worldexchange.com'
// const BASE_URL1 = 'https://ag.t20worldexchange.com'

const BASE_URL = 'https://ag.betever365.com'
const BASE_URL1 = "https://ag.betever365.com"

// const BASE_URL1 = "http://101.0.20.71:2930"

// const BASE_URL = 'https://ag.betever365.com'
// const BASE_URL1 = "https://ag.betever365.com"
const BASE_URL2 = 'https://betever365.com'

// const BASE_URL_API = 'https://casino.betever365.com';,
const BASE_URL_API = 'https://casino.maxxcric.com';
// const WEB_SOCKET_API = 'https://casino.fancy22.com';
// const BASE_URL = ''
// const BASE_URL1=''


// const BASE_URL_v1 = 'https://casino.betever365.com';
const BASE_URL_v1 = 'https://casino.maxxcric.com';
// const WEB_SOCKET_API = 'https://casino.betever365.com';
const WEB_SOCKET_API = 'https://casino.maxxcric.com';
// const BASE_URL_v1 = 'https://casino.betever365.com';
// const BASE_URL = 'https://fancy22.com';
// const BASE_URL1 = 'https://fancy22.com';


export const CONFIG = {

  // EXCHANGE CONFIGURATION URLS 

  // siteKey:'2',
  // SiteName:'exchange',
  agentLogin: BASE_URL + "/ag/login/agentLogin",
  getIpLocation: 'https://pro.ip-api.com/json/?key=qSA5ctYZHdWsx04',
  getThemeConfig: BASE_URL1 + "/api/exchange/theme/getThemeConfig",
  getThemeConfigTime: 1440,
  getAgentBalance: BASE_URL + "/ag/exchange/getAgentBalance",
  sportsList: BASE_URL1 + "/api/exchange/sports/sportsList",
  mSportsListTime: 1440,
  getAllEventsListTime: 20,
  getAllEventsList: BASE_URL2 + "/api/exchange/market/matchodds/allEventsList",
  getAgentRefreshBalance: BASE_URL + "/ag/exchange/getAgentRefreshBalance",
  sportTournamentsList: BASE_URL1 + "/api/exchange/tournaments/sportTournamentsList",
  tournamentEventsList: BASE_URL1 + "/api/exchange/events/tournamentEventsList",
  sportCompetitionsList: BASE_URL1 + "/api/exchange/competitions/sportCompetitionsList",
  competitionEventsList: BASE_URL1 + "/api/exchange/events/competitionEventsList",
  changeAgentPassword: BASE_URL + "/ag/exchange/account/changeAgentPassword",
  getUsersList: BASE_URL + "/ag/exchange/account/getUsersList",
  getAccountDetails: BASE_URL + "/ag/exchange/account/getAccountDetails",
  checkRegisterUser: BASE_URL + "/ag/exchange/account/checkRegisterUser",
  createAccount: BASE_URL + "/ag/exchange/account/createAccount",
  setDw: BASE_URL + "/ag/exchange/banking/setDw",
  updateExposureLimit: BASE_URL + "/ag/exchange/account/updateExposureLimit",
  getUserEventsExposure: BASE_URL + "/ag/exchange/marketanalysis/getUserEventsExposure",
  updateCreditReference: BASE_URL + "/ag/exchange/account/updateCreditReference",
  deleteUser: BASE_URL + "/ag/exchange/account/deleteUser",
  updateChipSummary: BASE_URL + "/ag/exchange/chipsummary/updateChipSummary",
  exportUsersDownline: BASE_URL + "/ag/exchange/userlist/exportUsersDownline",
  changeParentUserPassword: BASE_URL + "/ag/exchange/account/changeParentUserPassword",
  changeUsersStatus: BASE_URL + "/ag/exchange/account/changeUsersStatus",
  getCreditReferenceLogs: BASE_URL + "/ag/exchange/creditreference/getCreditReferenceLogs",
  getUserProfileData: BASE_URL + "/ag/exchange/account/getUserProfileData",
  userActivityList: BASE_URL + "/ag/exchange/activitylog/userActivityList",
  userAccountStatement: BASE_URL + "/ag/exchange/bankinglog/userAccountStatement",
  agentSportsProfitloss: BASE_URL + "/ag/exchange/profitloss/agentSportsProfitloss",
  mSportsList: BASE_URL1 + "/api/exchange/sports/mSportsList",
  getUserBetList: BASE_URL + "/ag/exchange/betlist/getUserBetList",
  agentEventsProfitloss: BASE_URL + "/ag/exchange/profitloss/agentEventsProfitloss",
  agentMarketsProfitloss: BASE_URL + "/ag/exchange/profitloss/agentMarketsProfitloss",
  getUserBetHistory: BASE_URL + "/ag/exchange/getlist/getUserBetHistory",
  masterActivityList: BASE_URL + "/ag/exchange/activitylog/masterActivityList",
  deleteUserList: BASE_URL + "/ag/exchange/account/deleteUserList",
  restoreUser: BASE_URL + "/ag/exchange/account/restoreUser",
  // master reports
  masterAccountStatement: BASE_URL + "/ag/exchange/banking/masterAccountStatement",
  getMasterBetList: BASE_URL + "/ag/exchange/betlist/getMasterBetList",
  getMasterUsersProfitloss: BASE_URL + "/ag/exchange/profitloss/getMasterUsersProfitloss",
  getPasswordChangeHistory: BASE_URL + "/ag/exchange/history/getPasswordChangeHistory",
  logOutAgent: BASE_URL + "/ag/exchange/logout/logOutAgent",
  marketAnalysisEvents: BASE_URL + "/ag/exchange/exposure/marketAnalysisEvents",
  getGetParentOfUser: BASE_URL + "/ag/exchange/marketanalysis/getGetParentOfUser",
  marketProfitLossList: BASE_URL + "/ag/exchange/profitloss/marketProfitLossList",
  getMarketsOfEventList: BASE_URL1 + "/api/exchange/markets/getMarketsEventList",


  // getMarketsOfEventList: BASE_URL1 + "/api/exchange/market/getMarketsOfEventList",
  getEventMarketsName: BASE_URL + "/ag/exchange/marketanalysis/getEventMarketsName",
  getMasterUserpl: BASE_URL + "/ag/exchange/marketanalysis/getMasterUserpl",
  setAllBetLockedUnLockUser: BASE_URL + '/ag/exchange/betlock/setAllBetLockedUnLockUser',
  getBetLockUnlockUserList: BASE_URL + '/ag/exchange/betlock/getBetLockUnlockUserList',
  setBetLockedUnLockUser: BASE_URL + "/ag/exchange/betlock/setBetLockedUnLockUser",
  storeFancyPlMaster: BASE_URL + "/ag/exchange/marketanalysis/storeFancyPlMaster",
  storeCBSPlMaster: BASE_URL + "/ag/exchange/marketanalysis/storeCBSPlMaster",
  getEventBetList: BASE_URL + "/ag/exchange/betlist/getEventBetList",
  getLiveEventBet: BASE_URL + "/ag/exchange/livebet/getLiveEventBet",
  getEventStreaming: BASE_URL + "/ag/exchange/streaming/getEventStreaming",
  videoStreamURL: WEB_SOCKET_API + '/casinoapp/exchange/users/streaming/casinoEventStreaming',

  getAgentFancyStorePl: BASE_URL + "/ag/exchange/storepl/getAgentFancyStorePl",
  getAgentUsersList: BASE_URL + "/ag/exchange/account/getAgentUsersList",
  updateUserRollingCommission: BASE_URL + "/ag/exchange/commission/updateUserRollingCommission",
  updateUserMobileNo: BASE_URL + "/ag/exchange/mobileno/updateUserMobileNo",
  updateUserPartnership: BASE_URL + "/ag/exchange/partnership/updateUserPartnership",
  plCallsTime: 5000,
  addNews: BASE_URL + "/ag/exchange/news/addNews",
  getNews: BASE_URL + "/ag/exchange/news/getNews",
  getSportsLivePlDashboard: BASE_URL + "/ag/exchange/profitloss/getSportsLivePlDashboard",
  getSportsBackupPlDashboard: BASE_URL + "/ag/exchange/profitloss/getSportsBackupPlDashboard",
  getSliderList: BASE_URL + "/ag/exchange/slider/getSliderList",
  getCommission: BASE_URL + "/ag/exchange/rcommission/master/total",
  saveSlider: BASE_URL + "/ag/exchange/slider/saveSlider",
  addNotification: BASE_URL + "/ag/exchange/notification/addNotification",
  transfered: BASE_URL + "/ag/exchange/rcommission/transfered",
  reject: BASE_URL + "/ag/exchange/rcommission/reject",
  deleteSlider: BASE_URL + "/ag/exchange/slider/deleteSlider",
  getMarketsEventList: BASE_URL + "/api/exchange/markets/getMarketsEventList",
  // getMarketsEventList: BASE_URL + "/api/exchange/market/getMarketsOfEventList",
  roleList: BASE_URL + "/ag/exchange/account/roleList",
  getsportsLockedList: BASE_URL + "/ag/exchange/betlock/getsportsLockedList",
  userSportsBetLocked: BASE_URL + "/ag/exchange/betlock/userSportsBetLocked",
  fancyMarketList: BASE_URL + "/api/exchange/markets/fancyMarketList",
  fancyMarketListTime: 1440,
  eventMatchedBetList: BASE_URL + "/app/exchange/users/betlist/eventMatchedBetList",
  getSportRules: BASE_URL + "/api/exchange/rules/getSportRules",
  sportsRulesList: BASE_URL + "/api/exchange/rules/sportsRulesList",
  getSportsRule: BASE_URL + '/api/exchange/rules/getSportsRule',
  getSupportData: BASE_URL + '/ag/exchange/support/getSupportData',
  deleteSupportData: BASE_URL + '/ag/exchange/support/deleteSupportData',
  parentuserEventsExposure: BASE_URL + "/ag/exchange/exposure/parentuserEventsExposure",
  userUsMarketListExposure: BASE_URL + "/ag/exchange/exposure/userUsMarketListExposure",
  updateSupportNumber: BASE_URL + "/ag/exchange/support/updateSupportNumber",
  updateUserMatchOddsCommission: BASE_URL + "/ag/exchange/commission/updateUserMatchOddsCommission",
  updateMasterRollingCommission: BASE_URL + "/ag/exchange/commission/updateMasterRollingCommission",
  racingEventsList: BASE_URL + '/api/exchange/events/racingEventsList',
  // casinoLobby: WEB_SOCKET_API + '/casinoapp/exchange/users/casino/casinoLobbyList',
  // casinoLobbyTime: 1440,
  disabled2FA: BASE_URL + "/app/exchange/users/auth/disabled2FA",
  checkSecureStatus: BASE_URL + "/app/exchange/users/auth/checkSecureStatus",
  disabled2FAOtpVerify: BASE_URL + "/ag/exchange/auth/disabled2FAOtpVerify",
  getConnectionId: BASE_URL + "/ag/exchange/teleauth/getConnectionId",

  // CASINO CONFIGURATION URLS 

  socketurl: BASE_URL + '',
  siteKey: '5',
  SiteName: 'Exchange',
  userLoginURL: WEB_SOCKET_API + "/casinoapp/exchange/casino/userCasinoLogin",
  getUserBalanceURL: WEB_SOCKET_API + "/casinoapp/exchange/users/balance/getUserBalance",
  asianCasinoPlacebetURL: WEB_SOCKET_API + "/casinoapp/exchange/users/casino/placebet",
  getCasinoEventOdds: WEB_SOCKET_API + "/casinoapp/exchange/users/pl/getCasinoPl",
  userGetStackURL: WEB_SOCKET_API + "/casinoapp/exchange/users/getUserBetStake",
  getRulesOfMarketURL: WEB_SOCKET_API + '/casinoapp/exchange/users/rules/casinoEventRules',
  getCasinoResultURL: WEB_SOCKET_API + '/casinoapp/users/casino/casinoEventResults',
  getAllMarketplURL: WEB_SOCKET_API + '/casinoapp/exchange/users/pl/getCasinoPl',

  casinoMatchedBetList: WEB_SOCKET_API + '/casinoapp/exchange/users/betlist/casinoMatchedBetList',
  getCasinoTheme: WEB_SOCKET_API + '/casinoapp/exchange/users/casino/casinoThemeConfig',
  // casinoLobby: WEB_SOCKET_API + '/api/exchange/users/casino/casinoLobby',
  casinoLobby: WEB_SOCKET_API + '/casinoapp/exchange/users/casino/casinoLobbyList',
  // updateUserBetStake: BASE_URL_API + "/app/exchange/users/updateUserBetStake",
  updateUserBetStake: BASE_URL_v1 + "/casinoapp/exchange/users/updateUserBetStake",
  casinoLobbyTime: 1440,
  // getThemeConfig: WEB_SOCKET_API + "/api/exchange/theme/getThemeConfig",
  // getThemeConfig: WEB_SOCKET_API + "/casinoapp/exchange/users/casino/getThemeConfig",
  // getThemeConfigTime: 1440,
  // getWhatsappNumber : BASE_URL_v1 + '/v1/exchange/users/getParentWhatsAppNo',
  userAuthURL: BASE_URL_v1 + "/user/login",
  getALLHomeMarketListURL: BASE_URL_v1 + "/front/all_events",
  placeLotteryBetURL: BASE_URL_v1 + '/exchange/user/lottery_placebet',
  getLotteryResultURL: BASE_URL_v1 + '/exchange/user/getlottery_result',
  getAllResultLotteryURL: BASE_URL_v1 + '/front/user/get_lotteryresult',
  getLotteryPlURL: BASE_URL_v1 + '/exchange/user/lottery_pl',
  userBetStakeList: BASE_URL + "/app/exchange/users/userBetStakeList",

  /* DIAMOND API  START */

  // getCasinoEventOdds: BASE_URL_API +'/api/exchange/users/odds/getCasinoEventOdds',
  verifyTokenURL: BASE_URL_API + '/api/exchange/casino/userCasinoLogin',
  // getUserBalanceURL: BASE_URL_API + "/api/exchange/users/balance/getUserBalance",
  // asianCasinoPlacebetURL: BASE_URL_API + '/api/exchange/users/casino/asian/placebet',
  eUCasinoPlacebetURL: BASE_URL_API + '/api/exchange/users/casino/european/placebet',
  virtualCasinoPlacebetURL: BASE_URL_API + "/casinoapp/exchange/users/casino/placebet",
  // userGetStackURL: BASE_URL_API + "/api/exchange/users/getUserBetStake",
  getDealerListURL: BASE_URL_API + '/api/exchange/users/dealers/getCasinoDealers',
  //  getCasinoResultURL: BASE_URL_API + '/api/exchange/users/casino/getCasinoMarketResults',
  getResultChartDataURL: BASE_URL_API + '/api/exchange/users/casino/getBaccaratResultGraph',
  //  getAllMarketplURL: BASE_URL_API + '/api/exchange/users/pl/getCasinoPl',
  logoutUserURL: BASE_URL_API + '/casinoapp/exchange/casino/logOutUser',
  // getRulesOfMarketURL: BASE_URL_API + '/api/exchange/users/rules/getSportsRules',
  getSelectionPL: BASE_URL_API + '/api/exchange/users/pl/getSelectionCasinoPl',
  // casinoMatchedBetList: BASE_URL_API+ '/api/exchange/users/betlist/casinoMatchedBetList',
  userUpdateStackValueURL: BASE_URL_API + "/api/exchange/users/updateUserBetStake",
  userEventsExposure: BASE_URL_API + "/casinoapp/exchange/users/userEventsExposure",
  // getCasinoTheme: BASE_URL_API + "/api/exchange/users/casino/getCasinoThemeConfig",
  // getAllEventsList: BASE_URL + "/api/exchange/market/matchodds/allEventsList",
  // getAllEventsListTime: 20,
  SearchEventList: BASE_URL + "/api/exchange/events/searchEventList",
  SearchEventListTime: 1440,
  SportsList: BASE_URL + "/api/exchange/sports/sportsList",
  SportsListTime: 1440,
  exchangeTypeList: BASE_URL + "/api/exchange/exchangeTypeList",
  exchangeTypeListTime: 1440,

  /* DIAMOND API  END */



  // CasinoSocketUrl: 'wss://casino.betever365.com/',
  // CasinoSocketUrl: 'wss://casino.fancy22.com/',
  // CasinoSocketUrl: 'wss://casino.betever365.com/',
  CasinoSocketUrl: 'wss://casino.maxxcric.com/',
  // CasinoSocketUrl: '',

  casninoTableURL: 'universe_casino_77',
  virtualTableURL: 'universe_casino_88',
  casninoTeenPatti: 'universe_casino_7710',
  dragontiger2020: 'universe_casino_7719',
  lucky7A: 'universe_casino_7730',
  bacarat: 'universe_casino_7701',
  bacaratA: 'universe_casino_7702',
  andarBahirA: 'universe_casino_7725',
  thirty2cardsA: 'universe_casino_7722',
  oneDayTeenPatti: 'universe_casino_7713',
  dragonTiger: 'universe_casino_7718',
  fastLucky7: 'universe_casino_7732',
  muflisTeenPatti: 'universe_casino_7714',
  dtl: 'universe_casino_7742',
  dtlA: 'universe_casino_7741',
  fastDragonTiger: 'universe_casino_7720',
  threeCardJudA: 'universe_casino_7740',
  ammarAkbarAnthony: 'universe_casino_7705',
  dltTeenPatti: 'universe_casino_7704',
  inaMinaDika: 'universe_casino_7706',
  instantWorli: 'universe_casino_7709',
  andarBahirC: 'universe_casino_7734',
  luck7B: 'universe_casino_7731',
  tewentyTewentyCardRace: 'universe_casino_7746',
  baccaratC: 'universe_casino_7736',
  thirty2cardB: 'universe_casino_7723',
  // new tables
  pocker2020: 'universe_casino_7707',
  pocker2020B: 'universe_casino_7708',
  pointTeenpatti: 'universe_casino_7715',
  jokerTeenpatti: 'universe_casino_7716',
  casinoMeter: 'universe_casino_7755',
  lottry: 'universe_casino_7758',
  kbc: 'universe_casino_7759',
  bollywood: 'universe_casino_7750',
  oneCardMeter: 'universe_casino_7751',
  trio: 'universe_casino_7760',
  jhandiMunda: 'universe_casino_7752',
  oneCard2020: 'universe_casino_7757',
  baccarat29cards: 'universe_casino_7756',
  oneDayDragonTiger: 'universe_casino_7721',
  casinoWar: 'universe_casino_7727',
  sicbo: 'universe_casino_7761',
  duskadam: 'universe_casino_7779',
  race2second: 'universe_casino_7780',

  userWithdrawBankList: BASE_URL + "/app/exchange/users/withdraw/userWithdrawBankList",
  addWithdrawalBank: BASE_URL + "/app/exchange/users/withdraw/addWithdrawalBank",
  calculateWithdrawAmt: BASE_URL + "/app/exchange/users/withdraw/calculateWithdrawAmt",
  deleteWithdrawBank: BASE_URL + "/app/exchange/users/withdraw/deleteWithdrawBank",
  bankList: BASE_URL + "/app/exchange/users/withdraw/bankList",
  withdrawalRequest: BASE_URL + "/app/exchange/users/withdraw/withdrawalRequest",
  cancelWithdrawalRequest: BASE_URL + "/app/exchange/users/withdraw/cancelWithdrawalRequest",
  lastestWithdrawURL: BASE_URL + "/app/exchange/users/withdraw/latestWithdrawalList",
  getMatchOddsPl: BASE_URL + "/app/exchange/users/pl/getMatchOddsPl",
  getFancyPl: BASE_URL + "/app/exchange/users/pl/getFancyPl",
  getSportsbookPl: BASE_URL + "/app/exchange/users/pl/getSportsbookPl",
  getBookmakersPl: BASE_URL + "/app/exchange/users/pl/getBookmakersPl",
  // getUserBetList: BASE_URL + "/app/exchange/users/betlist/getUserBetList",
  placebet: BASE_URL + "/app/exchange/users/placebet",
  // eventMatchedBetList: BASE_URL + "/app/exchange/users/betlist/eventMatchedBetList",
  unSettledBetList: BASE_URL + "/app/exchange/users/betlist/mobile/unSettledBetList",
  // fancyMarketList: BASE_URL + "/api/exchange/markets/fancyMarketList",
  // fancyMarketListTime: 1440,
  // sportTournamentsList: BASE_URL + '/api/exchange/tournaments/sportTournamentsList',
  // racingEventsList: BASE_URL + '/api/exchange/events/racingEventsList',
  racingEventsListTime: 20,
  userLogout: BASE_URL + '/app/exchange/users/userLogout',
  bannerList: BASE_URL + '/api/exchange/banner/bannerList',
  bannerListTime: 1440,
  virtualSportsList: BASE_URL + '/api/exchange/sports/virtualSportsList',
  virtualSportsListTime: 30,
  // getSportsRule: BASE_URL + '/api/exchange/rules/getSportsRule',
  tipsPreviewList: BASE_URL + '/api/exchange/tips/tipsPreviewList',
  tipsPreviewListTime: 30,
  favouritesExpriTime: 10,
  // getMarketsEventList: BASE_URL + "/api/exchange/markets/getMarketsEventList",
  sendUserRegisterOtp: BASE_URL + '/app/users/sendUserRegisterOtp',
  verifyUserRegisterOtp: BASE_URL + "/app/users/verifyUserRegisterOtp",
  sendForgotPasswordOtp: BASE_URL + "/app/users/sendForgotPasswordOtp",
  verifyForgotPassword: BASE_URL + "/app/users/verifyForgotPassword",
  // userAccountStatement: BASE_URL + "/app/exchange/users/userAccountStatement",
  userBalance: BASE_URL + "/app/exchange/users/userBalance",
  changedPasswordHistory: BASE_URL + "/app/exchange/users/changedPasswordHistory",
  userChangePassword: BASE_URL + "/app/exchange/users/userChangePassword",
  userActivityLogs: BASE_URL + "/app/exchange/users/userActivityLogs",
  userSportsProfitloss: BASE_URL + "/app/exchange/users/pl/userSportsProfitloss",
  userMarketsProfitloss: BASE_URL + "/app/exchange/users/pl/userMarketsProfitloss",
  userEventsProfitloss: BASE_URL + "/app/exchange/users/pl/userEventsProfitloss",
  userUnSettledBetList: BASE_URL + "/app/exchange/users/betlist/userUnSettledBetList",
  // sportsRulesList: BASE_URL + "/api/exchange/rules/sportsRulesList",
  sportsRulesListTime: 1440,
  userSettledBetList: BASE_URL + "/app/exchange/users/betlist/userSettledBetList",
  userSettleBetListCustomURL: BASE_URL + "/app/exchange/users/betlist/mobile/settledBetList",
  userAccountStatementCustomURL: BASE_URL + "/app/exchange/users/mobile/accountStatement",
  sliderList: BASE_URL + "/api/exchange/slider/sliderList",
  casinoEvents: BASE_URL + "/api/exchange/navigations/casinoEvents",
  casinoEventsTime: 1440,


}